stages:
  - build
  - deploy
before_script:
  - echo "Before script"
  - cd /var/www/html/laravel-vue
build:
  stage: build
  image: node
  script:
    - git pull
    - source ~/.nvm/nvm.sh
    - nvm -v
    - echo "Build successfully!"

test:
  stage: deploy
  image: node
  script:
    - echo "Disini Deploy Docker"
    - echo "Deploy successfully!"